"use client";

import { useState, useEffect } from "react";
import { DollarSign, Activity, Loader2 } from "lucide-react";
import { 
    LineChart, Line, BarChart, Bar, PieChart, Pie, Cell,
    XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer 
} from "recharts";

export default function AnalyticsDashboard() {
    // 1. Setup State for the incoming API data
    const [isLoading, setIsLoading] = useState(true);
    const [data, setData] = useState({
        financialData: [],
        marketData: [],
        usageData: [],
        liveFeeds: [],
        totalUnits: 0
    });

    // 2. Fetch the aggregated data on load
    useEffect(() => {
        const fetchAnalytics = async () => {
            try {
                const response = await fetch("http://127.0.0.1:8000/api/admin/analytics/dashboard");
                if (response.ok) {
                    const result = await response.json();
                    setData(result);
                }
            } catch (error) {
                console.error("Failed to load analytics:", error);
            } finally {
                setIsLoading(false);
            }
        };

        fetchAnalytics();
    }, []);
    
    // Custom Tooltip for the Financial Step Chart
    const CustomTooltip = ({ active, payload, label }: any) => {
        if (active && payload && payload.length) {
            return (
                <div className="bg-[#18181b] border border-zinc-700 p-3 rounded-xl shadow-xl">
                    <p className="text-zinc-300 text-sm font-medium mb-1">{label}</p>
                    <p className="text-emerald-400 font-bold text-sm">
                        margin : {payload[0].value}%
                    </p>
                </div>
            );
        }
        return null;
    };

    if (isLoading) {
        return (
            <div className="h-[80vh] flex flex-col items-center justify-center text-zinc-500">
                <Loader2 className="h-8 w-8 animate-spin mb-4 text-blue-500" />
                <p>Compiling global telemetry...</p>
            </div>
        );
    }

    return (
        <div className="space-y-6 pb-12">
            
            {/* Top Row: Financial (2/3) + Market (1/3) */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                
                {/* FINANCIAL OVERSIGHT */}
                <div className="lg:col-span-2 bg-[#111827]/40 border border-zinc-800/60 p-6 rounded-2xl shadow-sm flex flex-col">
                    <div className="flex justify-between items-start mb-8">
                        <div>
                            <h3 className="text-xl font-bold text-zinc-100">Financial Oversight</h3>
                            <p className="text-zinc-500 text-sm mt-1">Global Profit Margin Aggregation</p>
                        </div>
                        <div className="h-10 w-10 rounded-full bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
                            <DollarSign className="text-emerald-400" size={20} />
                        </div>
                    </div>
                    
                    <div className="flex-1 w-full min-h-[300px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={data.financialData} margin={{ top: 20, right: 20, left: -20, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" stroke="#27272a" vertical={false} />
                                <XAxis dataKey="day" stroke="#52525b" tick={{ fill: '#71717a', fontSize: 12 }} tickLine={false} axisLine={false} dy={10} />
                                <YAxis stroke="#52525b" tick={{ fill: '#71717a', fontSize: 12 }} tickLine={false} axisLine={false} tickFormatter={(val) => `${val}%`} />
                                <Tooltip content={<CustomTooltip />} cursor={{ stroke: '#3f3f46', strokeWidth: 1, strokeDasharray: '4 4' }} />
                                <Line type="stepAfter" dataKey="margin" stroke="#34d399" strokeWidth={3} dot={{ r: 5, fill: '#09090b', stroke: '#34d399', strokeWidth: 2 }} activeDot={{ r: 7, fill: '#34d399', stroke: '#fff', strokeWidth: 2 }} />
                            </LineChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* MARKET POPULARITY (Dynamically generated by Fleet Brands) */}
                <div className="bg-[#111827]/40 border border-zinc-800/60 p-6 rounded-2xl shadow-sm flex flex-col">
                    <h3 className="text-xl font-bold text-zinc-100 mb-6">Market Popularity</h3>
                    
                    <div className="relative h-48 w-full flex items-center justify-center mb-6">
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                                <Pie data={data.marketData} innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value" stroke="none">
                                    {data.marketData.map((entry: any, index: number) => (
                                        <Cell key={`cell-${index}`} fill={entry.color} />
                                    ))}
                                </Pie>
                            </PieChart>
                        </ResponsiveContainer>
                        
                        <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                            <span className="text-2xl font-bold text-white">{data.totalUnits}</span>
                            <span className="text-[10px] text-zinc-500 font-bold tracking-wider uppercase">Global Units</span>
                        </div>
                    </div>

                    <div className="space-y-3 flex-1 overflow-y-auto pr-2 custom-scrollbar max-h-[150px]">
                        {data.marketData.map((item: any) => (
                            <div key={item.name} className="flex items-center justify-between bg-zinc-900/50 p-3 rounded-xl border border-zinc-800/50">
                                <div className="flex items-center gap-3">
                                    <div className="h-2 w-2 rounded-full shrink-0" style={{ backgroundColor: item.color }}></div>
                                    <span className="text-sm font-semibold text-zinc-200 truncate">{item.name}</span>
                                </div>
                                <span className="text-sm font-bold text-white">{item.value}</span>
                            </div>
                        ))}
                    </div>
                </div>

            </div>

            {/* Bottom Row: Digital Twin Logs */}
            <div className="bg-[#111827]/40 border border-zinc-800/60 p-6 rounded-2xl shadow-sm">
                
                <div className="flex justify-between items-start mb-8 border-b border-zinc-800/60 pb-6">
                    <div>
                        <h3 className="text-xl font-bold text-zinc-100">Digital Twin Usage Logs</h3>
                        <p className="text-zinc-500 text-sm mt-1">Platform Engagement Tracking</p>
                    </div>
                    <div className="px-3 py-1.5 rounded-full border border-blue-900/50 bg-blue-900/20 text-blue-400 text-[10px] font-bold tracking-wider uppercase">
                        Live Data Feed
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-5 gap-12">
                    
                    {/* Bar Chart Area */}
                    <div className="lg:col-span-3 h-[250px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={data.usageData} margin={{ top: 0, right: 0, left: 0, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" stroke="#27272a" vertical={false} />
                                <XAxis dataKey="day" stroke="#52525b" tick={{ fill: '#71717a', fontSize: 12 }} tickLine={false} axisLine={false} dy={10} />
                                <Tooltip cursor={{ fill: '#27272a', opacity: 0.4 }} contentStyle={{ backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: '8px' }} />
                                <Bar dataKey="hours" fill="#4f8aff" radius={[4, 4, 0, 0]} barSize={45} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>

                    {/* LIVE TICKETS LIST! */}
                    <div className="lg:col-span-2 space-y-4">
                        {data.liveFeeds.length > 0 ? data.liveFeeds.map((feed: any) => (
                            <div key={feed.id} className="flex items-center justify-between bg-zinc-900/40 hover:bg-zinc-900/80 transition-colors p-4 rounded-xl border border-zinc-800/60">
                                <div className="flex items-center gap-4 overflow-hidden">
                                    <div className="h-10 w-10 rounded-lg bg-[#18181b] border border-zinc-800 flex items-center justify-center shrink-0">
                                        <Activity className="text-blue-500" size={18} />
                                    </div>
                                    <div className="truncate pr-2">
                                        <h4 className="text-sm font-bold text-zinc-100 truncate">{feed.company}</h4>
                                        <p className="text-[10px] text-zinc-500 font-mono mt-0.5 uppercase truncate">{feed.robot}</p>
                                    </div>
                                </div>
                                <div className="text-right shrink-0">
                                    <span className="text-sm font-bold text-blue-400 block">{feed.time}</span>
                                    <span className={`text-[9px] font-bold tracking-wider uppercase mt-0.5 block ${feed.status === 'HIGH' ? 'text-red-400' : 'text-zinc-600'}`}>
                                        {feed.status} PRIORITY
                                    </span>
                                </div>
                            </div>
                        )) : (
                            <div className="h-full flex flex-col items-center justify-center text-zinc-500 border-2 border-dashed border-zinc-800/50 rounded-xl p-6">
                                <p className="text-sm font-medium">No live telemetry detected.</p>
                                <p className="text-xs">Service tickets will appear here instantly.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}